int WORKER_AIM = 10;//todo настроить
int SOLDIER_AIM = 10;
int POLICEMAN_AIM = 10;
int INITIAL_PEST_COUNT = 20;

int WORKER_CONSUMED_FOOD = 1;
int POLICEMAN_CONSUMED_FOOD = 2;
int SOLDIER_CONSUMED_FOOD = 3;
int ANT_QUEEN_CONSUMED_FOOD = 4;
int LARVA_CONSUMED_FOOD = 2;
int PEST_CONSUMED_FOOD = 2;

int LARVA_BIRTH_COUNT = 3;
int PEST_KILL_COUNT = 2;
int COLLECTED_FOOD_COUNT = 10;
double FOOD_INCREASE_PERCENTAGE = 1.03;